#!/usr/bin/env bash
# This is mostly a helper script for Docker.
# Activates virtualenv, then runs twistd in the foreground under authbind
source .tox/py27/bin/activate
authbind twistd --nodaemon c101ws
