#!/usr/bin/env bash
# This is mostly a helper script for Docker.
# Activates virtualenv, then runs twistd in the foreground as nobody.
# The usual security issues with using nobody don't apply: we're containerized.
source .tox/py27/bin/activate
twistd --nodaemon --uid=`id -u nobody` --gid=`id -g nobody` c101ws
